PyCQA/docformatter

- docformatter.py
- test_docformatter.py
This is not recommended by the PEP 257, but there are some project that
use it in this way. So, a new '--make-summary-multiline' option is added
to allow those project to be able to use the rest of the docformatter
features.
When this option is set as True and use docformatter over a function
like this one:
```python
def function():
"""This is a one line summary that will be converted to multiline."""
```
the result will be:
```python
def function():
"""
This is a one line summary that will be converted to multiline.
"""
```
> New '--make-summary-multiline' option

- docformatter.py
- test_docformatter.py
Adds support for argument lists like:
```Args:
x: the first argument
y: the second argument
```
Currently the system works for these already, kind of.  If the docstring looks like:
```python
def f(x, y):
"""The identity function.
Returns what you give it.
Args:
x: the argument
y: ignored
"""
return x
```
then docformatter does the right thing and leaves it alone.  But if the comment looks like:
```python
def f(x, y):
"""The identity function.
Args:
x: the argument
y: ignored
"""
return x
```
(note the missing second paragraph) then docformatter suggests
```python
def f(x):
"""The identity function.
Args:   x: the argument   y: ignored
"""
return x
```
Which it seems like is a bug. This updates the code to work properly in this case and adds a corresponding test case.
> Support colon-separated argument lists

- .pre-commit-hooks.yaml
See pre-commit documentation at https://pre-commit.com.
This makes it convenient for people to automatically run docfomatter
when committing code to their codebase.
[Example usage](https://github.com/akbiggs/challonge-tools/blob/master/.pre-commit-config.yaml#L7).
> Add pre-commit hooks for docformatter

- docformatter.py
- test_docformatter.py
This closes #22.
Please review, and if accepted, create new release of docformatter( This issue is affecting me, as it prevents using docformatter in pre-commit hooks - leads to changes in file only due to line endings, and conflicts with reorder_python_imports)
> Support Windows-style line endings

- docformatter.py
- test_docformatter.py
Fixes the issue described here: https://github.com/myint/docformatter/issues/16
> A pydoc reference such as ':see:' should not be start of sentence

- README.rst
- docformatter.py
- setup.py
- test_docformatter.py
Added a simple exclude command line option which can be used to exclude folders and files. Further site-packages get excluded.
Exclusion can be triggered via the `-e` or `--exclude` flag following multiple folder or file names e.g. `-e <folder> <folder> <file>`. Files and folders are excluded in the `find_py_files` method via `re.search`.
> Added command line exclude option

- .gitignore
- docformatter.py
- test_docformatter.py
close #62 
In this PR:
1. I've added `--docstring-length` flag to limit editing docstrings to those of given length (especially useful when refactoring big projects)
2. Added unit tests for this feature and two utils
> Add --docstring-length flag

- README.rst
- docformatter.py
- test_docformatter.py
I submit for your consideration a potential solution to issue #10 .
This adds two functions:
* One to find the config file specified with the new --config option and compare it against a list of supported config files (currently only pyproject.toml).
* A second function to read the contents of the config file into a dict which is returned to _main().
The dict is used to set default values in the add_argument() methods, thus ensuring command line options take precedence.  Adding additional config files (e.g., setup.cfg, tox.ini) should be reasonably trivial with these functions.
Four tests have been added to the test suite to test these two functions and a section added to the README to explain the use of pyproject.toml.  All tests pass as well as all static checks.  I've been successfully …
> Add pyproject.toml support for config (Issue #10)

- docformatter.py
- pyproject.toml
- setup.py
- test_docformatter.py
- tests/test_string_functions.py
This adds support for raw and unicode docstrings.  The type identifier can be either lower case or upper case (r, R, u, U).  The formatted docstring will retain the type identifier in the same case.
Cleaned up some linting and style warnings.
Closes #54.
> fix: add support for raw and unicode docstrings

- .gitignore
- README.rst
- docformatter.py
- pyproject.toml
- test_docformatter.py
- tests/_data/pyproject.toml
- tests/test_utility_functions.py
The conditional in is_some_sort_of_list() function was identifying the README example
```
def launch_rocket():
"""Launch
the
rocket. Go colonize space."""
```
as a list because it was being processed as many lines of short words.  This required the --force-wrap argument to be set to produce the desired result.
This PR adds a new argument `--non-strict` to control the execution of this conditional.  Since the list format it is searching for is a non-standard reST list, this argument is assigned a default value of False.  Passing it on the command line or setting it True in the configuration file will restore current behavior (i.e., not strictly following reST).
Also adds some bling to the top of the README.
Closes #67
> fix: add argument to turn on/off many lines of short words being a list

- docformatter.py
- test_docformatter.py
This was caused by the conditional introduced to strip the newline between a function definition and the docstring.  It was looking for a newline token that was two lines after a function definition (i.e., starts with 'def' and ends with ':').  This didn't account for a potential in-line comment which inserts another token before the '\n'.  When the '\n' following the in-line comment token was processed the above conditions were met and the '\n' was stripped.
This PR changes the condition so when a newline token is processed, it looks to see if the previous line was a newline and two lines after a function definition (i.e., starts with 'def' and ends with a ':' or a comment).
Closes #97
Closes #98
> fix: definitions corrupted with in-line comment

- README.rst
- docformatter.py
- test_docformatter.py
- tests/_data/setup.cfg
- tests/_data/tox.ini
- tests/test_configuration_functions.py
- tests/test_format_docstring.py
This PR moves all the configuration business to a new class and adds support for setup.cfg and tox.ini.  docformatter will also now search the current directory for one of the supported configuration files and use the first one found if no file is explicitly passed (defaults to pyproject.toml).  Command line arguments still take precedence.
Closes #92
> feat: add support for setup.cfg and tox.ini configuration files

- README.rst
- docformatter.py
- pyproject.toml
- tests/test_format_docstring.py
A new argument `--close-quotes-on-newline` was added to allow the closing triple quotes to be placed on a newline when a one-line docstring is wrapped and takes two or more lines.  The default value is false to avoid breaking current use-cases.
Closes #9
> feat: add option to place closing quotes on newline

- .github/workflows/ci.yml
- .gitignore
- docformatter.py
- docs/source/configuration.rst
- docs/source/requirements.rst
- pyproject.toml
- tests/test_configuration_functions.py
- tests/test_format_docstring.py
Adds function and associated tests to reconnect URLs that are broken into parts when docstrings are wrapped.
Closes #75
> fix: don't wrap URLs

- .github/workflows/ci.yml
- docformatter.py
- pyproject.toml
- tests/test_format_code.py
- tests/test_format_docstring.py
- tests/test_string_functions.py
Class attribute docstrings will be wrapped.  The first letter of the docstring summary will be capitalized.
Closes #76
Closes #83
> feat: format class attribute docstrings

- src/docformatter/configuration.py
- src/docformatter/format.py
- tests/test_docformatter.py
It can be useful to show the difference, e.g. in CI so that users know what is or should be changed.
This adds a `--diff` option, that, when combined with `--check` or `--in-place`, will, in addition, show the diff to stdout.
fix #125
> Allow showing the diff when using --in-place or --check with --diff

- .github/workflows/ci.yml
Ubuntu latest is transitioning to 22.04 which doesn't support Python 3.6.  This sets the ci workflow runner explicitly to Ubuntu 20.04 to allow the Python 3.6 test suite to run.
> chore: update CI workflow so 3.6 still runs

- src/docformatter/format.py
- tests/test_format_code.py
This pull request address part of #130. That is, the rule that there should be no blank lines before class or method docstrings. I've not addressed the other part of that issue, which is that there should be no blank lines after a function/method docstring but there should be one (and only one) blank line after a class docstring.
> No empty lines before class and method docstrings

- src/docformatter/configuration.py
- tests/conftest.py
- tests/test_docformatter.py
Boolean options were always set as True when read from pyproject.toml.  This was the result of reading a string, which always returns a True when converted to boolean.  Defaults are now set using a "==".  Added tests to explicitly test configuration options read from pyproject.toml.
Closes #119
> Fix incorrect pyproject.toml parsing of boolean values

- README.rst
- docs/source/usage.rst
- src/docformatter/configuration.py
- src/docformatter/format.py
- tests/conftest.py
- tests/test_configuration_functions.py
- tests/test_docformatter.py
Adds new options that can be set in the config files.  These include --check, --diff, --in-place, and --exclude.  Also has docformatter exit with non-zero even when --in-place changes files.
Closes #120, #121, #122
> feat: add file config options

- .github/workflows/do-release.yml
- src/docformatter/format.py
- tests/test_format_code.py
This will remove blank lines following a method docstring.  See requirement PEP_257_4.4.
Closes #130.
> fix: remove blank line after method docstring

- src/docformatter/syntax.py
- tests/test_format_docstring.py
This pull request:
* Skips link handling when there is nothing wrapped in the original text.
* Maintains wraps when the link is short enough to be contained on a single line along with additional words.
Closes #140
> fix: handle index error in link wrapping

- .github/workflows/do-release.yml
- src/docformatter/syntax.py
- tests/test_docformatter.py
- tests/test_format_docstring.py
This pull request fixes the problem with docformatter not wrapping long descriptions that have multiple paragraphs.
Closes #127
> fix: wrap multi-paragraph long descriptions

- CHANGELOG.md
- docs/source/requirements.rst
- src/docformatter/encode.py
- tests/test_encoding_functions.py
- tests/test_format_docstring.py
Found via `codespell -S .tox -L dedented,pullrequests`
> docs: fix typos

- .github/workflows/ci.yml
- README.rst
- pyproject.toml
- tests/test_utility_functions.py
Drops support for Python 3.6 (one year post end-of-life).
Updates dependencies to latest versions.
Closes #118
> chore: drop support for Python3.6

- .github/workflows/ci.yml
- .github/workflows/do-release.yml
- .github/workflows/do-update-authors.yml
- .github/workflows/on-push-tag.yml
Updates action versions.
Changes commit message to conventional commit format for action to update AUTHORS.rst.
Add steps to create GitHub (pre-)release when release candidate tag is pushed and upload wheel to release.
Move steps to upload wheels and test install on release tags to tags action.
> chore: update GitHub action workflows

- docs/source/requirements.rst
- src/docformatter/__pkginfo__.py
Update requirements documentation to clarify which arguments are to be added in future releases.  Update version info in missed file.
Closes #167
> docs: clarify future arguments

- .github/workflows/ci.yml
- docs/source/usage.rst
- src/docformatter/__init__.py
- src/docformatter/__main__.py
- src/docformatter/__pkginfo__.py
- src/docformatter/configuration.py
- src/docformatter/encode.py
- src/docformatter/format.py
- src/docformatter/strings.py
- src/docformatter/syntax.py
- src/docformatter/util.py
- tests/__init__.py
- tests/conftest.py
- tests/test_configuration_functions.py
- tests/test_docformatter.py
- tests/test_encoding_functions.py
- tests/test_format_code.py
- tests/test_format_docstring.py
- tests/test_utility_functions.py
Fixes problem with blank lines between methods/functions being removed when the last line in the first function began with "def".
Closes #156 
Closes #165
Closes #172
Closes #173
> fix: remove blank lines after line beginning with 'def'

- docs/source/conf.py
- pyproject.toml
- src/docformatter/__pkginfo__.py
- src/docformatter/format.py
- tests/test_format_code.py
Fixes problem removing blank line after docstring in stub functions.
Closes #156
Closes #161
> release: v1.6.1

- src/docformatter/format.py
- tests/test_format_docstring.py
Fixes problem with docformatter removing the blank following a class docstring when the docstring is followed by a comment.
Closes #176.
> fix: remove blank after comment

- src/docformatter/strings.py
- tests/test_format_docstring.py
- tests/test_string_functions.py
Fixes the issue with docformatter adding a blank line in a summary that is wrapped and the second line begins with a symbol.
Closes #79.
> fix: adding blank line in summary with symbol

- src/docformatter/format.py
- src/docformatter/strings.py
- tests/test_format_code.py
> fix: removing newline after shebang

- docs/source/configuration.rst
- docs/source/requirements.rst
- docs/source/usage.rst
- src/docformatter/configuration.py
- src/docformatter/format.py
- src/docformatter/strings.py
- tests/conftest.py
- tests/test_configuration_functions.py
- tests/test_format_docstring.py
> feat: add option for user to provide list of words not to capitalize

- .pre-commit-config.yaml
- README.rst
- docs/source/installation.rst
- pyproject.toml
- src/docformatter/__init__.py
- src/docformatter/configuration.py
- src/docformatter/format.py
- src/docformatter/strings.py
- src/docformatter/syntax.py
Use tomllib to read pyproject.toml with Python >=3.11.
Closes #170
> feat: use tomllib for Python 3.11+

- README.rst
- docs/source/configuration.rst
- docs/source/requirements.rst
- docs/source/usage.rst
- pyproject.toml
- src/docformatter/__main__.py
- src/docformatter/syntax.py
- tests/test_format_docstring.py
Adds wrapping support for Epytext style field lists.
> feat: support epytext style

- .github/workflows/do-prioritize-issues.yml
- .pre-commit-config.yaml
- src/docformatter/syntax.py
- tests/test_format_docstring.py
Fixes the problem with reST directives being split up when they contain two words surrounded by colons (#215).
Fixes the problem with quoted URLs being wrapped after the opening quote (#217).
Fixes the problem with Sphinx field lists not having all the white space removed before wrapping (#218).
Closes #215 
Closes #217 
Closes #218
> fix: wrapping issues with reST directives, quoted URLs, and Sphinx field lists

- .github/workflows/do-prioritize-issues.yml
- .github/workflows/do-release.yml
- .github/workflows/on-push-tag.yml
Move the job to autogenerate the CHANGELOG.md to the tag work flow instead of the release workflow.  Need the tag to keep the CHANGELOG.md up to date and the release workflow comes before the tag.
> chore: move changelog to tag workflow

- src/docformatter/syntax.py
- tests/_data/string_files/format_sphinx.toml
- tests/formatter/test_format_sphinx.py
Adds `yield` to the list of sphinx field names.
Closes #253
> fix: not recognizing `yield` as a sphinx field name

- docs/source/requirements.rst
- pyproject.toml
Closes #260
This caused Sphinx to fail to render the entire table.
After this change, the Sphinx error has gone away and the table renders:
> Add missing comma in requirements table

- src/docformatter/syntax.py
- tests/_data/string_files/do_format_docstrings.toml
- tests/formatter/test_do_format_docstring.py
- tests/test_syntax_functions.py
> Do not double-process urls

- tests/test_utility_functions.py
https://github.com/testing-cabal/mock
mock is now part of the Python standard library, available as [unittest.mock](https://docs.python.org/dev/library/unittest.mock.html) in Python 3.3 onwards.
> prefer new unittest.mock from the standard library

- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
- pyproject.toml
- src/docformatter/syntax.py
[pre-commit just released v4.0.0](https://github.com/pre-commit/pre-commit/releases/tag/v4.0.0) with the breaking change that `language: python_venv` was removed.
This breaks `docformatter` hook config at parse time, even for users that don't use `docformatter-venv` (e.g. I use the "normal" `docformatter` hook).
The error is:
```py
An error has occurred: InvalidManifestError: 
==> File /home/runner/.cache/pre-commit/repocernquz3/.pre-commit-hooks.yaml
==> At Hook(id='docformatter-venv')
==> At key: language
=====> Expected one of conda, coursier, dart, docker, docker_image, dotnet, fail, golang, haskell, lua, node, perl, pygrep, python, r, ruby, rust, script, swift, system but got: 'python_venv'
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
```
In addition to removing …
> 🩹 Fix pre commit hook manifest

- src/docformatter/configuration.py
- src/docformatter/strings.py
- tests/test_string_functions.py
This PR adds a new function to split a multi-sentence summary into the first sentence, which becomes the summary, and the remaining sentences which get prepended to the long description.
Fixes #283.
> fix: multi sentence summary

- README.rst
- src/docformatter/syntax.py
The example in the README can't be produced because the 'Launch the rocket.' line gets picked up as a list is unformatted unlike in the example.  For now the README will be updated until the list-like detection code is updated.
> fix: update README example

- poetry.lock
- pyproject.toml
This updates dependency and tool versions.  Closes security vulnerability #2.
> chore: updating dependency and tool versions

- README.rst
- docs/source/conf.py
- docs/source/usage.rst
- src/docformatter/classify.py
- src/docformatter/constants.py
- src/docformatter/encode.py
- src/docformatter/format.py
- src/docformatter/patterns/fields.py
- src/docformatter/patterns/lists.py
- src/docformatter/patterns/misc.py
- src/docformatter/patterns/rest.py
- src/docformatter/patterns/url.py
- src/docformatter/strings.py
- src/docformatter/wrappers/description.py
- src/docformatter/wrappers/summary.py
- tests/_data/string_files/description_wrappers.toml
- tests/_data/string_files/do_format_code.toml
- tests/_data/string_files/do_format_docstrings.toml
- tests/_data/string_files/rest_patterns.toml
- tests/_data/string_files/string_functions.toml
- tests/patterns/test_rest_patterns.py
Address most of the issues reported in #321.  A new release/v1.7.8 branch will be created for testing the release candidate and tracking the fixes to issues identified rather than using a release candidate tag.  The tag causes pre-commit autoupdate to use potentially buggy code which is not the preferred approach for me as it causes unnecessary heartache for user who choose not to participate in testing.
> fix: issue 321
